# Generated by Django 5.1.1 on 2024-09-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Minecraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
