# Generated by Django 5.1.1 on 2024-09-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Minecraft', '0002_alter_server_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-kills']},
        ),
    ]
